groups/urls.py
from django.urls import path
from . import views

app_name='groups'

urlpatterns = [
    path('new-group/', views.CreateGroup.as_view(), name='group_create'),
    path('group-all/', views.ListGroup.as_view(), name='group_list'),
    path('group/<slug>/', views.DetailGroup.as_view(), name='single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('groups/', include('groups.urls', namespace="groups")),
    path('questions/', include('questions.urls', namespace="questions")),
]

questions/urls.py
from django.urls import path
from . import views


app_name="questions"


urlpatterns = [
    path('', views.QuestionListView.as_view(), name='question_list'),
    path('create-question/', views.QuestionCreateView.as_view(), name='question_create'),
    path('<pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
]

questions/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

from django.contrib.auth import get_user_model
from groups.models import Group
# Create your models here.

User = get_user_model()

class Question(models.Model):
    author = models.ForeignKey(User, related_name="questions", on_delete=models.CASCADE, null=True)
    question = models.CharField(max_length=600)
    url = models.URLField(blank=True)
    create_date = models.DateTimeField(default=timezone.now)

    group = models.ManyToManyField(Group,through='GroupPost', blank=True)

    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse('questions:question-detail', kwargs={'pk':self.pk})


    class Meta:
        ordering = ['-create_date']
        unique_together = ['author','question']




class Category(models.Model):
    name = models.CharField(max_length=90, unique=True)
    question_category = models.ManyToManyField(Question, through='QuestionCategory', blank=True)

    def __str__(self):
        return self.name

class QuestionCategory(models.Model):
    question = models.ForeignKey(Question, related_name="question_cat", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='cat', on_delete=models.CASCADE)

    def __str__(self):
        return self.category.name

    class Meta:
        unique_together=('question','category')


class GroupPost(models.Model):
    question = models.ForeignKey(Question, related_name="question_post", on_delete=models.CASCADE)
    group = models.ForeignKey(Group, related_name='group_post', on_delete=models.CASCADE)

    def __str__(self):
        return self.group.name

    class Meta:
        unique_together=('question','group')

questions/forms.py
from django import forms
from . import models

class QuestionForm(forms.ModelForm):

    class Meta():
        model = models.Question
        fields = ("question","url")


        widgets = {
            'question': forms.Textarea(attrs={
                'class':'postcontent',
            })
        }

questions/views.py
from django.shortcuts import render
from django.utils import timezone

from .models import Question
from .forms import QuestionForm

from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.views.generic import (ListView, DetailView,
                                  UpdateView, CreateView,
                                  DeleteView)
# Create your views here.


class QuestionListView(ListView):
    model = Question


    def get_queryset(self):
        return Question.objects.filter(
            create_date__lte=timezone.now()).order_by('-create_date')



class QuestionCreateView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    model = Question

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)



class QuestionDetailView(DetailView):
    # model = Question

    def get_queryset(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        return Question.objects.filter(pk=pk)

questions/templates/questions/question_base.html
{% extends 'base.html'%}


{% block content %}

<div class="row">

  <div class="col-lg-2">
    {% block left_arm %}

    {% endblock %}
  </div>

  <div class="col-lg-7">
    {% block middle_arm %}

    {% endblock %}
  </div>

  <div class="col-lg-3">
    {% block right_arm %}

    {% endblock %}
  </div>

</div>

{% endblock %}

questions/templates/questions/question_detail.html
{% extends 'questions/question_base.html' %}
{% load bootstrap5 %}
{% load static %}

{% block middle_arm %}
  <h3>{{question.question}}</h3>
{% endblock %}

questions/templates/questions/question_form.html
{% extends 'questions/question_base.html' %}
{% load static %}
{% load bootstrap5%}

{% block middle_arm %}

<h4>Expole your query!</h4>
<form id="postFrom" action="{% url 'questions:question_create' %}" method="POST">
  {%csrf_token%}
  {% bootstrap_form form %}
  {% buttons %}
        <button type="submit" class="btn btn-primary">Ask</button>
        <a class='btn btn-primary' href="{% url 'questions:question_list' %}"> Cancel</a>
  {% endbuttons %}
</form>

{% endblock %}

questions/templates/questions/question_list.html
{% extends 'questions/question_base.html' %}
{% load my_extras %}

{% block left_arm %}
<h4>Create a Question</h4>
<a class="btn btn-outline-primary btn-sm" href="{% url 'questions:question_create'%}" role="button">Create</a>

{% endblock %}



{% block middle_arm %}

  {% for question in question_list %}
    <div class="list-group">
      <a href="{% url 'questions:question_detail' pk=question.pk %}" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{question.question}}</h5>
          <!-- <small>3 days ago</small> -->
          <small>{{question.create_date|post_duration}} days ago</small>
        </div>
        <p class="mb-1">{{question.url}}</p>
        <small>And some small print.</small>
      </a>
    </div>

  {% endfor %}

{% endblock %}


{% block right_arm %}
<h4>Categories List</h4>
  <button class="btn btn-outline-secondary btn-sm float-sm-start" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
    Find</button>

  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
      <h5 id="offcanvasRightLabel">Most popular categories</h5>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <ul class="list-group">
        <a href="#" style='text-decoration: none;'> <li class="list-group-item">An active item</li> </a>
        <a href="#" style='text-decoration: none;'> <li class="list-group-item">A second item</li> </a>
        <a href="#" style='text-decoration: none;'> <li class="list-group-item">A third item</li> </a>
        <a href="#" style='text-decoration: none;'> <li class="list-group-item">A fourth item</li> </a>
        <a href="#" style='text-decoration: none;'> <li class="list-group-item">And a fifth one</li> </a>
      </ul>
    </div>
  </div>
{% endblock %}