groups/urls.py
from django.urls import path
from . import views

app_name='groups'

urlpatterns = [
    path('new-group/', views.CreateGroup.as_view(), name='group_create'),
    path('group-all/', views.ListGroup.as_view(), name='group_list'),
    path('group/<slug>/', views.DetailGroup.as_view(), name='single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('groups/', include('groups.urls', namespace="groups")),
    path('questions/', include('questions.urls', namespace="questions")),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django import template
from django.urls import reverse
# from questions.models import Question

from django.contrib.auth import get_user_model


User = get_user_model()
register = template.Library()


# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    owner = models.CharField(max_length=200)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default="",blank=True)

    member = models.ManyToManyField(User, through='GroupMember')
    # group_post = models.ManyToManyField(Question, through='Post', blank=True)


    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})




class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memeberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username


    class Meta:
        unique_together = ('group','user')

groups/forms.py
from .models import Group
from django import forms
from django.forms.widgets import HiddenInput


class GroupForm(forms.ModelForm):
    class Meta:
        fields = ('name', 'owner', 'description')
        model = Group


    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)
        self.fields['owner'].widget =HiddenInput()

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)

from django.urls import reverse
from django.views import generic
from groups.models import Group, GroupMember

from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import IntegrityError

from questions.forms import QuestionForm
# from groups.forms import  GroupForm
# Create your views here.



class CreateGroup(LoginRequiredMixin, generic.CreateView):
    # form_class = GroupForm
    fields = ('name', 'description')
    model = Group

    def form_valid(self, form):
        print('#'*8)
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        print(f'Form object: {self.object.owner}')
        return super().form_valid(form)


class ListGroup(generic.ListView):
    # model = Group

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Group.objects.all()


class DetailGroup(LoginRequiredMixin, generic.DetailView):
    # model = Group

    def get_queryset(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        return Group.objects.filter(slug=slug)




class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.get_or_create(user=self.request.user, group=group)
        except IntegrityError:
            messages.add_message(self.request, messages.WARNING,
                                 "Warning, you already a member of {}".format(group))
        else:
            messages.add_message(self.request, messages.SUCCESS, 'Now, you are a member!')

        return super().get(request, *args, **kwargs)



class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})


    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(user = self.request.user,group__slug=self.kwargs.get('slug')).get()

        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry, you are not in this group!')

        else:
            membership.delete()
            messages.success(self.request, 'Successfully, you are left this group')

        return super().get(request, *args, **kwargs)



# Group Post


def group_post_create(request):
    pass

groups/templates/groups/group_base.html
{% extends 'base.html'%}
{% load static %}
{% load bootstrap5 %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'groups/css/master.css' %}">
{% endblock%}


{% block content %}

<div class="row">
  <div class="col-lg-2">
    {% block left_arm%}
    {% endblock%}
  </div>

  <div class="col-lg-8">
    {% block middle_arm %}
    {% endblock %}
  </div>

  <div class="col-lg-2">
    {% block right_arm %}
    {% endblock %}
  </div>

</div>

<script type="text/javascript" src="{% static 'groups/js/groupstyle.js' %}">

</script>
{% endblock%}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block left_arm %}
    <div class="">

      <h2><span> {{ group.name }} </span> &nbsp&nbsp
        <span><a class="btn btn-outline-primary btn-sm" href="{% url 'groups:leave' slug=group.slug %}" role="button">Leave</a> </span></h2>

        <div class="">
          <small><span> Owner: {{group.owner}} </span> &nbsp&nbsp&nbsp&nbsp
          <span> Members: {{group.member.count}} </span></small>
        </div>

        <div class="">

          <figure>
            <blockquote class="blockquote">
              <p>{{ group.description_html|safe }}</p>
            </blockquote>
            <figcaption class="blockquote-footer">
              Owner
            </figcaption>
          </figure>

        </div>
    </div>


{% endblock %}

{% block middle_arm %}
  <div class="mb-3">
    <form class="" method="POST"> {% csrf_token %}
      <label for="exampleFormControlTextarea1" class="form-label"> <h2> Explore </h2> </label>
      {{ group.group_user_post.question.question}}
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
      <input style="margin-top:10px;" type="button" class='btn btn-primary' name="" value="Post">

    </form>
  </div>


  <h3>Recently Posts</h3>

  {% for post in group.group_post.all %}
    <p class="lead"> {{post.question.question}} </p>
    <p class="lead"> {{post.question.url}} </p>
  {% endfor %}


{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block middle_arm %}
  <h3> Create a new group! </h3>

  <div class="">
      <form id="groupForm" action="{% url 'groups:group_create'%}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
              <button type="submit" class="btn btn-primary">Create</button>
        {% endbuttons %}
      </form>
  </div>

{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
{% load static %}

{% block left_arm %}
<h3>Create your own Group</h3>
<a class="btn btn-outline-primary btn-sm" href="{% url 'groups:group_create' %}" role="button">Create</a>


{% endblock %}


{% block middle_arm %}

  <h2>All Groups!</h2>
  {% for group in group_list %}
  <div class="accordion accordion-flush" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header group_head" > <!-- id="flush-headingOne" -->
      <button class="accordion-button collapsed " type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
        {{group.name}}
      </button>
    </h2>

    <!-- Group Body -->
    <!-- id="flush-collapseOne" -->
    <div class="accordion-collapse collapse group_body" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        {{ group.description }}<br><br>

        <div class="btn-group d-grid gap-2 d-md-block">
          <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-outline-primary btn-sm" >Join</a>
          <a href="{% url 'groups:single' slug=group.slug %}" class="btn btn-outline-primary btn-sm">More!</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
{% endblock%}