accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

groups/urls.py
from django.urls import path
from . import views

app_name='groups'

urlpatterns = [
    path('new-group/', views.CreateGroup.as_view(), name='group_create'),
    path('group-all/', views.ListGroup.as_view(), name='group_list'),
    path('group/<slug>/', views.DetailGroup.as_view(), name='single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('groups/', include('groups.urls', namespace="groups")),
    path('questions/', include('questions.urls', namespace="questions")),
]

questions/urls.py
from django.urls import path
from . import views


app_name="questions"


urlpatterns = [
    path('', views.QuestionListView.as_view(), name='question_list'),
    path('create-question/', views.QuestionCreateView.as_view(), name='question_create'),
    path('<pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Explore</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '' %}">
    <!-- Font Family -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Padauk&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Russo+One&display=swap" rel="stylesheet">
    {% block css_link %}

    {% endblock%}
  </head>
  <body>

    {% include 'navbar.html' %}

    <div class="container-fluid">

      {% block content %}
      {% endblock %}

      <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script> -->

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Index Page!</h1>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'questions:question_list' %}"> <span style="font-family: 'Pacifico', cursive; color:#ffb01f;">E </span> <span style="font-family: 'Pacifico', cursive;font-family: 'Padauk', sans-serif;">xplore</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link " href="#">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'questions:question_list' %}">Question</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'groups:group_list' %}">Group</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'accounts:logout' %}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'accounts:signup' %}">Sign Up</a>
        </li>
        <!--
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="false">Group</a>
        </li>
          -->
        {% endif %}
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>